package com.oltpbenchmark.schema;

import java.util.Collections;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import com.oltpbenchmark.benchmarks.tpcc.TPCCConstants;

public class TPCCTableSchemas {
    public static final Map<String, TableSchema> tables = Collections.unmodifiableMap(Stream.of(
            new TableSchemaBuilder(TPCCConstants.TABLENAME_ORDERLINE)
                .column("ol_w_id", "int NOT NULL")
                .column("ol_d_id", "int NOT NULL")
                .column("ol_o_id", "int NOT NULL")
                .column("ol_number", "int NOT NULL")
                .column("ol_i_id", "int NOT NULL")
                .column("ol_delivery_d", "timestamp NULL DEFAULT NULL")
                .column("ol_amount", "decimal(6,2) NOT NULL")
                .column("ol_supply_w_id", "int NOT NULL")
                .column("ol_quantity", "decimal(2,0) NOT NULL")
                .column("ol_dist_info", "char(24) NOT NULL")
                .primaryKey("((ol_w_id,ol_d_id) HASH,ol_o_id,ol_number)")
                .partitionKey("(ol_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_NEWORDER)
                .column("no_w_id", "int NOT NULL")
                .column("no_d_id", "int NOT NULL")
                .column("no_o_id", "int NOT NULL")
                .primaryKey("((no_w_id,no_d_id) HASH,no_o_id)")
                .partitionKey("(no_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_STOCK)
                .column("s_w_id", "int NOT NULL")
                .column("s_i_id", "int NOT NULL")
                .column("s_quantity", "decimal(4,0) NOT NULL")
                .column("s_ytd", "decimal(8,2) NOT NULL")
                .column("s_order_cnt", "int NOT NULL")
                .column("s_remote_cnt", "int NOT NULL")
                .column("s_data", "varchar(50) NOT NULL")
                .column("s_dist_01", "char(24) NOT NULL")
                .column("s_dist_02", "char(24) NOT NULL")
                .column("s_dist_03", "char(24) NOT NULL")
                .column("s_dist_04", "char(24) NOT NULL")
                .column("s_dist_05", "char(24) NOT NULL")
                .column("s_dist_06", "char(24) NOT NULL")
                .column("s_dist_07", "char(24) NOT NULL")
                .column("s_dist_08", "char(24) NOT NULL")
                .column("s_dist_09", "char(24) NOT NULL")
                .column("s_dist_10", "char(24) NOT NULL")
                .primaryKey("(s_w_id HASH, s_i_id ASC)")
                .partitionKey("(s_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_OPENORDER)
                .column("o_w_id", "int NOT NULL")
                .column("o_d_id", "int NOT NULL")
                .column("o_id", "int NOT NULL")
                .column("o_c_id", "int NOT NULL")
                .column("o_carrier_id", "int DEFAULT NULL")
                .column("o_ol_cnt", "decimal(2,0) NOT NULL")
                .column("o_all_local", "decimal(1,0) NOT NULL")
                .column("o_entry_d", "timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP")
                .primaryKey("((o_w_id,o_d_id) HASH,o_id)")
                .partitionKey("(o_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_HISTORY)
                .column("h_c_id", "int NOT NULL")
                .column("h_c_d_id", "int NOT NULL")
                .column("h_c_w_id", "int NOT NULL")
                .column("h_d_id", "int NOT NULL")
                .column("h_w_id", "int NOT NULL")
                .column("h_date", "timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP")
                .column("h_amount", "decimal(6,2) NOT NULL")
                .column("h_data",  "varchar(24) NOT NULL")
                .partitionKey("(h_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_CUSTOMER)
                .column("c_w_id", "int NOT NULL")
                .column("c_d_id", "int NOT NULL")
                .column("c_id", "int NOT NULL")
                .column("c_discount", "decimal(4,4) NOT NULL")
                .column("c_credit", "char(2) NOT NULL")
                .column("c_last", "varchar(16) NOT NULL")
                .column("c_first", "varchar(16) NOT NULL")
                .column("c_credit_lim", "decimal(12,2) NOT NULL")
                .column("c_balance", "decimal(12,2) NOT NULL")
                .column("c_ytd_payment", "float NOT NULL")
                .column("c_payment_cnt", "int NOT NULL")
                .column("c_delivery_cnt", "int NOT NULL")
                .column("c_street_1", "varchar(20) NOT NULL")
                .column("c_street_2", "varchar(20) NOT NULL")
                .column("c_city", "varchar(20) NOT NULL")
                .column("c_state", "char(2) NOT NULL")
                .column("c_zip", "char(9) NOT NULL")
                .column("c_phone", "char(16) NOT NULL")
                .column("c_since", "timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP")
                .column("c_middle", "char(2) NOT NULL")
                .column("c_data", "varchar(500) NOT NULL")
                .primaryKey("((c_w_id,c_d_id) HASH,c_id)")
                .partitionKey("(c_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_DISTRICT)
                .column("d_w_id", "int NOT NULL")
                .column("d_id", "int NOT NULL")
                .column("d_ytd", "decimal(12,2) NOT NULL")
                .column("d_tax", "decimal(4,4) NOT NULL")
                .column("d_next_o_id", "int NOT NULL")
                .column("d_name", "varchar(10) NOT NULL")
                .column("d_street_1", "varchar(20) NOT NULL")
                .column("d_street_2", "varchar(20) NOT NULL")
                .column("d_city", "varchar(20) NOT NULL")
                .column("d_state", "char(2) NOT NULL")
                .column("d_zip", "char(9) NOT NULL")
                .primaryKey("((d_w_id,d_id) HASH)")
                .partitionKey("(d_w_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_ITEM)
                .column("i_id", "int NOT NULL")
                .column("i_name", "varchar(24) NOT NULL")
                .column("i_price", "decimal(5,2) NOT NULL")
                .column("i_data", "varchar(50) NOT NULL")
                .column("i_im_id", "int NOT NULL")
                .primaryKey("(i_id)")
                .build(),
            new TableSchemaBuilder(TPCCConstants.TABLENAME_WAREHOUSE)
                .column("w_id", "int NOT NULL")
                .column("w_ytd", "decimal(12,2) NOT NULL")
                .column("w_tax", "decimal(4,4) NOT NULL")
                .column("w_name", "varchar(10) NOT NULL")
                .column("w_street_1", "varchar(20) NOT NULL")
                .column("w_street_2", "varchar(20) NOT NULL")
                .column("w_city", "varchar(20) NOT NULL")
                .column("w_state", "char(2) NOT NULL")
                .column("w_zip", "char(9) NOT NULL")
                .primaryKey("(w_id)")
                .partitionKey("(w_id)")
                .build()
            ).collect(Collectors.toMap(TableSchema::name, e -> e)));
    
    public static TableSchema getTableSchema(String tablename) {
        return tables.get(tablename);
    }
}
